import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Montserrat } from "next/font/google";

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

import "./globals.css";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full ${montserrat.className} antialiased`}>
      <body className="min-h-full flex flex-col gap-3">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
